import Link from "next/link";
import { formatDistanceToNow } from "date-fns";
import { moderateContent } from "@/actions/staff";
import { StaffActionForm } from "@/components/staff/action-form";
import { requireModerator } from "@/lib/auth";
import { db } from "@/lib/db";
import { getModerationSettings } from "@/lib/moderation";
import { decodeCursor, encodeCursor } from "@/lib/queries";

export default async function StaffContentPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireModerator();
  const params = await searchParams;
  const q = params.q?.trim().slice(0, 100);
  const status = ["PUBLISHED", "HIDDEN", "DELETED"].includes(params.status ?? "") ? params.status as "PUBLISHED" | "HIDDEN" | "DELETED" : undefined;
  const kind = params.type === "REPLY" ? "REPLY" : params.type === "THREAD" ? "THREAD" : undefined;
  const cursor = decodeCursor<{ createdAt: string; id: string }>(params.cursor);
  const cursorTime = cursor && !Number.isNaN(Date.parse(cursor.createdAt)) ? new Date(cursor.createdAt) : null;
  const cursorWhere = cursorTime && cursor?.id ? { OR: [{ createdAt: { lt: cursorTime } }, { createdAt: cursorTime, id: { lt: cursor.id } }] } : undefined;
  const [threads, replies, settings] = await Promise.all([
    kind === "REPLY" ? [] : db.thread.findMany({ where: { status, OR: q ? [{ title: { contains: q, mode: "insensitive" } }, { body: { contains: q, mode: "insensitive" } }, { author: { username: { contains: q, mode: "insensitive" } } }] : undefined, AND: cursorWhere }, include: { author: { select: { username: true } }, category: { select: { name: true } } }, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take: 51 }),
    kind === "THREAD" ? [] : db.reply.findMany({ where: { status, OR: q ? [{ body: { contains: q, mode: "insensitive" } }, { author: { username: { contains: q, mode: "insensitive" } } }, { thread: { title: { contains: q, mode: "insensitive" } } }] : undefined, AND: cursorWhere }, include: { author: { select: { username: true } }, thread: { select: { slug: true, title: true } } }, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take: 51 }),
    getModerationSettings(),
  ]);
  const fetched = [...threads.map((item) => ({ kind: "THREAD" as const, ...item })), ...replies.map((item) => ({ kind: "REPLY" as const, ...item }))].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime() || b.id.localeCompare(a.id)).slice(0, 51);
  const items = fetched.slice(0, 50); const last = items.at(-1); const nextCursor = fetched.length > 50 && last ? encodeCursor({ createdAt: last.createdAt.toISOString(), id: last.id }) : null;
  return <section><div className="eyebrow">Review</div><h2 className="mt-1 text-2xl font-black">Forum content <span className="pill ml-2">{items.length}</span></h2><form action="/staff/content" className="card my-4 grid gap-3 p-4 sm:grid-cols-[1fr_150px_150px_auto]"><input className="input" name="q" defaultValue={q} placeholder="Search content or author" aria-label="Search content" /><select className="input" name="type" defaultValue={kind ?? ""} aria-label="Content type"><option value="">Threads and replies</option><option>THREAD</option><option>REPLY</option></select><select className="input" name="status" defaultValue={status ?? ""} aria-label="Content status"><option value="">Any status</option><option>PUBLISHED</option><option>HIDDEN</option><option>DELETED</option></select><button className="button button-secondary">Filter</button></form><div className="space-y-3">{items.map((item) => { const reasonsId = `content-reasons-${item.kind.toLowerCase()}-${item.id}`; const actions = item.kind === "THREAD" ? [item.status === "HIDDEN" ? "RESTORE" : "HIDE", item.isLocked ? "UNLOCK" : "LOCK", item.isPinned ? "UNPIN" : "PIN"] : [item.status === "HIDDEN" ? "RESTORE" : "HIDE"]; return <article className="card p-4" key={`${item.kind}-${item.id}`}><div className="flex flex-wrap items-center gap-2 text-xs muted"><span className="pill">{item.kind.toLowerCase()}</span><span className="pill">{item.status.toLowerCase()}</span><span>@{item.author.username}</span><span>· {formatDistanceToNow(item.createdAt, { addSuffix: true })}</span></div><Link className="mt-2 block font-black" href={item.kind === "THREAD" ? `/t/${item.slug}` : `/t/${item.thread.slug}#reply-${item.id}`}>{item.kind === "THREAD" ? item.title : item.thread.title}</Link><p className="mt-2 line-clamp-2 whitespace-pre-wrap text-sm muted">{item.body}</p>{item.status !== "DELETED" && <StaffActionForm action={moderateContent} className="mt-3 grid gap-2 sm:grid-cols-[140px_1fr_auto]"><input type="hidden" name="targetType" value={item.kind} /><input type="hidden" name="targetId" value={item.id} /><select className="input" name="action" aria-label={`${item.kind.toLowerCase()} moderation action`}>{actions.map((action) => <option key={action}>{action}</option>)}</select><input className="input" name="reason" list={reasonsId} placeholder="Reason" aria-label={`${item.kind.toLowerCase()} moderation reason`} required /><datalist id={reasonsId}>{settings.actionReasons.map((reason) => <option key={reason} value={reason} />)}</datalist><button className="button button-secondary">Apply</button></StaffActionForm>}</article>; })}{!items.length && <div className="card p-10 text-center muted">No content matches these filters.</div>}</div>{nextCursor ? <div className="mt-4 text-right"><Link className="button button-secondary" href={{ pathname: "/staff/content", query: { ...params, cursor: nextCursor } }}>More content</Link></div> : null}</section>;
}
