import { Bookmark } from "lucide-react";
import { ThreadCard } from "@/components/forum/thread-card";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { threadListInclude } from "@/lib/queries";
import { decodeCursor, encodeCursor } from "@/lib/queries";

export const dynamic = "force-dynamic";
export default async function BookmarksPage({ searchParams = Promise.resolve({}) }: { searchParams?: Promise<{ cursor?: string }> } = {}) { const user = await requireUser(); const { cursor: rawCursor } = await searchParams; const cursor = decodeCursor<{ createdAt: string; id: string }>(rawCursor); const cursorTime = cursor && !Number.isNaN(Date.parse(cursor.createdAt)) ? new Date(cursor.createdAt) : null; const bookmarks = await db.bookmark.findMany({ where: { userId: user.id, thread: { status: "PUBLISHED", category: { archivedAt: null }, author: { status: "ACTIVE" } }, AND: cursorTime && cursor?.id ? { OR: [{ createdAt: { lt: cursorTime } }, { createdAt: cursorTime, threadId: { lt: cursor.id } }] } : undefined }, include: { thread: { include: threadListInclude } }, orderBy: [{ createdAt: "desc" }, { threadId: "desc" }], take: 26 }); const visible = bookmarks.slice(0, 25); const last = visible.at(-1); const nextCursor = bookmarks.length > 25 && last ? encodeCursor({ createdAt: last.createdAt.toISOString(), id: last.threadId }) : null; return <div className="shell max-w-4xl py-9"><div className="eyebrow flex items-center gap-2"><Bookmark size={14} /> Your library</div><h1 className="mt-1 text-3xl font-black">Saved discussions</h1><div className="mt-7 space-y-3">{visible.length ? visible.map(({ thread }) => <ThreadCard key={thread.id} thread={thread} />) : <div className="card p-10 text-center"><h2 className="font-bold">Nothing saved yet</h2><p className="mt-1 muted">Bookmark useful discussions to find them here.</p></div>}</div>{nextCursor && <div className="mt-4 text-center"><a className="button button-secondary" href={`/bookmarks?cursor=${encodeURIComponent(nextCursor)}`}>More bookmarks</a></div>}</div>; }
